# Generated by Django 4.0.4 on 2022-05-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_profle_image_feed_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='is_marked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.TextField(null=True),
        ),
    ]
