# Generated by Django 4.0.4 on 2022-06-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='배달주소')),
                ('order_date', models.DateField(verbose_name='주문일')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='아이템 이름')),
                ('image_url', models.CharField(max_length=200, verbose_name='이미지 원본 링크')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
        migrations.CreateModel(
            name='item_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(verbose_name='아이템 갯수')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orders')),
            ],
        ),
    ]
