# Generated by Django 4.0.4 on 2022-06-21 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_expose_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='글 마지막 업데이트 일'),
            preserve_default=False,
        ),
    ]
