# Generated by Django 4.0.4 on 2023-02-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
