# Generated by Django 4.0.4 on 2022-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='취미')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(max_length=50, verbose_name='소개'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(to='user.hobby', verbose_name='취미'),
        ),
    ]
