# Generated by Django 4.0 on 2022-06-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_type_id',
            new_name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company_id',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_area',
            field=models.ManyToManyField(through='post.CompanyBusinessArea', to='post.BusinessArea'),
        ),
    ]
