# Generated by Django 4.0.4 on 2022-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_skillset_job_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(default=100000000),
            preserve_default=False,
        ),
    ]
