# Generated by Django 4.0.4 on 2022-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('profile_image', models.TextField()),
            ],
        ),
    ]
