# Generated by Django 4.0.4 on 2022-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=256)),
            ],
        ),
    ]
